// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datagram.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "datagram.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace subt {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* Datagram_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Datagram_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_datagram_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_datagram_2eproto() {
  protobuf_AddDesc_datagram_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "datagram.proto");
  GOOGLE_CHECK(file != NULL);
  Datagram_descriptor_ = file->message_type(0);
  static const int Datagram_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, src_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, dst_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, dst_port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, rssi_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, data_),
  };
  Datagram_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Datagram_descriptor_,
      Datagram::default_instance_,
      Datagram_offsets_,
      -1,
      -1,
      -1,
      sizeof(Datagram),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Datagram, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_datagram_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Datagram_descriptor_, &Datagram::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_datagram_2eproto() {
  delete Datagram::default_instance_;
  delete Datagram_reflection_;
}

void protobuf_AddDesc_datagram_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_datagram_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016datagram.proto\022\tsubt.msgs\"b\n\010Datagram\022"
    "\023\n\013src_address\030\001 \001(\t\022\023\n\013dst_address\030\002 \001("
    "\t\022\020\n\010dst_port\030\003 \001(\r\022\014\n\004rssi\030\004 \001(\001\022\014\n\004dat"
    "a\030\005 \001(\014b\006proto3", 135);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datagram.proto", &protobuf_RegisterTypes);
  Datagram::default_instance_ = new Datagram();
  Datagram::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_datagram_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_datagram_2eproto {
  StaticDescriptorInitializer_datagram_2eproto() {
    protobuf_AddDesc_datagram_2eproto();
  }
} static_descriptor_initializer_datagram_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Datagram::kSrcAddressFieldNumber;
const int Datagram::kDstAddressFieldNumber;
const int Datagram::kDstPortFieldNumber;
const int Datagram::kRssiFieldNumber;
const int Datagram::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Datagram::Datagram()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:subt.msgs.Datagram)
}

void Datagram::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Datagram::Datagram(const Datagram& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:subt.msgs.Datagram)
}

void Datagram::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  src_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dst_address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dst_port_ = 0u;
  rssi_ = 0;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Datagram::~Datagram() {
  // @@protoc_insertion_point(destructor:subt.msgs.Datagram)
  SharedDtor();
}

void Datagram::SharedDtor() {
  src_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dst_address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Datagram::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Datagram::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Datagram_descriptor_;
}

const Datagram& Datagram::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datagram_2eproto();
  return *default_instance_;
}

Datagram* Datagram::default_instance_ = NULL;

Datagram* Datagram::New(::google::protobuf::Arena* arena) const {
  Datagram* n = new Datagram;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Datagram::Clear() {
// @@protoc_insertion_point(message_clear_start:subt.msgs.Datagram)
  src_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dst_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dst_port_ = 0u;
  rssi_ = 0;
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Datagram::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:subt.msgs.Datagram)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string src_address = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_src_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->src_address().data(), this->src_address().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "subt.msgs.Datagram.src_address"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dst_address;
        break;
      }

      // optional string dst_address = 2;
      case 2: {
        if (tag == 18) {
         parse_dst_address:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dst_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dst_address().data(), this->dst_address().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "subt.msgs.Datagram.dst_address"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_dst_port;
        break;
      }

      // optional uint32 dst_port = 3;
      case 3: {
        if (tag == 24) {
         parse_dst_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &dst_port_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_rssi;
        break;
      }

      // optional double rssi = 4;
      case 4: {
        if (tag == 33) {
         parse_rssi:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rssi_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_data;
        break;
      }

      // optional bytes data = 5;
      case 5: {
        if (tag == 42) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:subt.msgs.Datagram)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:subt.msgs.Datagram)
  return false;
#undef DO_
}

void Datagram::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:subt.msgs.Datagram)
  // optional string src_address = 1;
  if (this->src_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->src_address().data(), this->src_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "subt.msgs.Datagram.src_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->src_address(), output);
  }

  // optional string dst_address = 2;
  if (this->dst_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dst_address().data(), this->dst_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "subt.msgs.Datagram.dst_address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->dst_address(), output);
  }

  // optional uint32 dst_port = 3;
  if (this->dst_port() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->dst_port(), output);
  }

  // optional double rssi = 4;
  if (this->rssi() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->rssi(), output);
  }

  // optional bytes data = 5;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:subt.msgs.Datagram)
}

::google::protobuf::uint8* Datagram::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:subt.msgs.Datagram)
  // optional string src_address = 1;
  if (this->src_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->src_address().data(), this->src_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "subt.msgs.Datagram.src_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->src_address(), target);
  }

  // optional string dst_address = 2;
  if (this->dst_address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dst_address().data(), this->dst_address().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "subt.msgs.Datagram.dst_address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->dst_address(), target);
  }

  // optional uint32 dst_port = 3;
  if (this->dst_port() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->dst_port(), target);
  }

  // optional double rssi = 4;
  if (this->rssi() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->rssi(), target);
  }

  // optional bytes data = 5;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:subt.msgs.Datagram)
  return target;
}

int Datagram::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:subt.msgs.Datagram)
  int total_size = 0;

  // optional string src_address = 1;
  if (this->src_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->src_address());
  }

  // optional string dst_address = 2;
  if (this->dst_address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dst_address());
  }

  // optional uint32 dst_port = 3;
  if (this->dst_port() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->dst_port());
  }

  // optional double rssi = 4;
  if (this->rssi() != 0) {
    total_size += 1 + 8;
  }

  // optional bytes data = 5;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Datagram::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:subt.msgs.Datagram)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Datagram* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Datagram>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:subt.msgs.Datagram)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:subt.msgs.Datagram)
    MergeFrom(*source);
  }
}

void Datagram::MergeFrom(const Datagram& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:subt.msgs.Datagram)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.src_address().size() > 0) {

    src_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.src_address_);
  }
  if (from.dst_address().size() > 0) {

    dst_address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dst_address_);
  }
  if (from.dst_port() != 0) {
    set_dst_port(from.dst_port());
  }
  if (from.rssi() != 0) {
    set_rssi(from.rssi());
  }
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void Datagram::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:subt.msgs.Datagram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Datagram::CopyFrom(const Datagram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:subt.msgs.Datagram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Datagram::IsInitialized() const {

  return true;
}

void Datagram::Swap(Datagram* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Datagram::InternalSwap(Datagram* other) {
  src_address_.Swap(&other->src_address_);
  dst_address_.Swap(&other->dst_address_);
  std::swap(dst_port_, other->dst_port_);
  std::swap(rssi_, other->rssi_);
  data_.Swap(&other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Datagram::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Datagram_descriptor_;
  metadata.reflection = Datagram_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Datagram

// optional string src_address = 1;
void Datagram::clear_src_address() {
  src_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Datagram::src_address() const {
  // @@protoc_insertion_point(field_get:subt.msgs.Datagram.src_address)
  return src_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_src_address(const ::std::string& value) {
  
  src_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:subt.msgs.Datagram.src_address)
}
 void Datagram::set_src_address(const char* value) {
  
  src_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:subt.msgs.Datagram.src_address)
}
 void Datagram::set_src_address(const char* value, size_t size) {
  
  src_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:subt.msgs.Datagram.src_address)
}
 ::std::string* Datagram::mutable_src_address() {
  
  // @@protoc_insertion_point(field_mutable:subt.msgs.Datagram.src_address)
  return src_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Datagram::release_src_address() {
  // @@protoc_insertion_point(field_release:subt.msgs.Datagram.src_address)
  
  return src_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_allocated_src_address(::std::string* src_address) {
  if (src_address != NULL) {
    
  } else {
    
  }
  src_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), src_address);
  // @@protoc_insertion_point(field_set_allocated:subt.msgs.Datagram.src_address)
}

// optional string dst_address = 2;
void Datagram::clear_dst_address() {
  dst_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Datagram::dst_address() const {
  // @@protoc_insertion_point(field_get:subt.msgs.Datagram.dst_address)
  return dst_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_dst_address(const ::std::string& value) {
  
  dst_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:subt.msgs.Datagram.dst_address)
}
 void Datagram::set_dst_address(const char* value) {
  
  dst_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:subt.msgs.Datagram.dst_address)
}
 void Datagram::set_dst_address(const char* value, size_t size) {
  
  dst_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:subt.msgs.Datagram.dst_address)
}
 ::std::string* Datagram::mutable_dst_address() {
  
  // @@protoc_insertion_point(field_mutable:subt.msgs.Datagram.dst_address)
  return dst_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Datagram::release_dst_address() {
  // @@protoc_insertion_point(field_release:subt.msgs.Datagram.dst_address)
  
  return dst_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_allocated_dst_address(::std::string* dst_address) {
  if (dst_address != NULL) {
    
  } else {
    
  }
  dst_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dst_address);
  // @@protoc_insertion_point(field_set_allocated:subt.msgs.Datagram.dst_address)
}

// optional uint32 dst_port = 3;
void Datagram::clear_dst_port() {
  dst_port_ = 0u;
}
 ::google::protobuf::uint32 Datagram::dst_port() const {
  // @@protoc_insertion_point(field_get:subt.msgs.Datagram.dst_port)
  return dst_port_;
}
 void Datagram::set_dst_port(::google::protobuf::uint32 value) {
  
  dst_port_ = value;
  // @@protoc_insertion_point(field_set:subt.msgs.Datagram.dst_port)
}

// optional double rssi = 4;
void Datagram::clear_rssi() {
  rssi_ = 0;
}
 double Datagram::rssi() const {
  // @@protoc_insertion_point(field_get:subt.msgs.Datagram.rssi)
  return rssi_;
}
 void Datagram::set_rssi(double value) {
  
  rssi_ = value;
  // @@protoc_insertion_point(field_set:subt.msgs.Datagram.rssi)
}

// optional bytes data = 5;
void Datagram::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Datagram::data() const {
  // @@protoc_insertion_point(field_get:subt.msgs.Datagram.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:subt.msgs.Datagram.data)
}
 void Datagram::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:subt.msgs.Datagram.data)
}
 void Datagram::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:subt.msgs.Datagram.data)
}
 ::std::string* Datagram::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:subt.msgs.Datagram.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Datagram::release_data() {
  // @@protoc_insertion_point(field_release:subt.msgs.Datagram.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Datagram::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:subt.msgs.Datagram.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace subt

// @@protoc_insertion_point(global_scope)
