// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: neighbor_m.proto

#ifndef PROTOBUF_neighbor_5fm_2eproto__INCLUDED
#define PROTOBUF_neighbor_5fm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "ignition/msgs/stringmsg_v.pb.h"
// @@protoc_insertion_point(includes)

namespace subt {
namespace msgs {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_neighbor_5fm_2eproto();
void protobuf_AssignDesc_neighbor_5fm_2eproto();
void protobuf_ShutdownFile_neighbor_5fm_2eproto();

class Neighbor_M;

// ===================================================================

class Neighbor_M : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:subt.msgs.Neighbor_M) */ {
 public:
  Neighbor_M();
  virtual ~Neighbor_M();

  Neighbor_M(const Neighbor_M& from);

  inline Neighbor_M& operator=(const Neighbor_M& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Neighbor_M& default_instance();

  void Swap(Neighbor_M* other);

  // implements Message ----------------------------------------------

  inline Neighbor_M* New() const { return New(NULL); }

  Neighbor_M* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Neighbor_M& from);
  void MergeFrom(const Neighbor_M& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Neighbor_M* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .ignition.msgs.StringMsg_V> neighbors = 1;
  int neighbors_size() const;
  void clear_neighbors();
  static const int kNeighborsFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::ignition::msgs::StringMsg_V >&
      neighbors() const;
  ::google::protobuf::Map< ::std::string, ::ignition::msgs::StringMsg_V >*
      mutable_neighbors();

  // @@protoc_insertion_point(class_scope:subt.msgs.Neighbor_M)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::ignition::msgs::StringMsg_V,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 >
      Neighbor_M_NeighborsEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::ignition::msgs::StringMsg_V,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > neighbors_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_neighbor_5fm_2eproto();
  friend void protobuf_AssignDesc_neighbor_5fm_2eproto();
  friend void protobuf_ShutdownFile_neighbor_5fm_2eproto();

  void InitAsDefaultInstance();
  static Neighbor_M* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Neighbor_M

// map<string, .ignition.msgs.StringMsg_V> neighbors = 1;
inline int Neighbor_M::neighbors_size() const {
  return neighbors_.size();
}
inline void Neighbor_M::clear_neighbors() {
  neighbors_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::ignition::msgs::StringMsg_V >&
Neighbor_M::neighbors() const {
  // @@protoc_insertion_point(field_map:subt.msgs.Neighbor_M.neighbors)
  return neighbors_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::ignition::msgs::StringMsg_V >*
Neighbor_M::mutable_neighbors() {
  // @@protoc_insertion_point(field_mutable_map:subt.msgs.Neighbor_M.neighbors)
  return neighbors_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace subt

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_neighbor_5fm_2eproto__INCLUDED
