// Generated by gencpp from file subt_ros/CompetitionClock.msg
// DO NOT EDIT!


#ifndef SUBT_ROS_MESSAGE_COMPETITIONCLOCK_H
#define SUBT_ROS_MESSAGE_COMPETITIONCLOCK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_ros
{
template <class ContainerAllocator>
struct CompetitionClock_
{
  typedef CompetitionClock_<ContainerAllocator> Type;

  CompetitionClock_()
    : phase()
    , data()  {
    }
  CompetitionClock_(const ContainerAllocator& _alloc)
    : phase(_alloc)
    , data()  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _phase_type;
  _phase_type phase;

   typedef ros::Time _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::subt_ros::CompetitionClock_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_ros::CompetitionClock_<ContainerAllocator> const> ConstPtr;

}; // struct CompetitionClock_

typedef ::subt_ros::CompetitionClock_<std::allocator<void> > CompetitionClock;

typedef boost::shared_ptr< ::subt_ros::CompetitionClock > CompetitionClockPtr;
typedef boost::shared_ptr< ::subt_ros::CompetitionClock const> CompetitionClockConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_ros::CompetitionClock_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_ros::CompetitionClock_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_ros::CompetitionClock_<ContainerAllocator1> & lhs, const ::subt_ros::CompetitionClock_<ContainerAllocator2> & rhs)
{
  return lhs.phase == rhs.phase &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_ros::CompetitionClock_<ContainerAllocator1> & lhs, const ::subt_ros::CompetitionClock_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_ros::CompetitionClock_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_ros::CompetitionClock_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_ros::CompetitionClock_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_ros::CompetitionClock_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_ros::CompetitionClock_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_ros::CompetitionClock_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_ros::CompetitionClock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5bf0940a1f496a721ee234c73e60109";
  }

  static const char* value(const ::subt_ros::CompetitionClock_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5bf0940a1f496a7ULL;
  static const uint64_t static_value2 = 0x21ee234c73e60109ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_ros::CompetitionClock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_ros/CompetitionClock";
  }

  static const char* value(const ::subt_ros::CompetitionClock_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_ros::CompetitionClock_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents subt competition clock.\n"
"\n"
"# The current phase: \"setup\", \"run\", or \"finished\"\n"
"string phase\n"
"\n"
"# Count down clock data for the current period.\n"
"time data\n"
;
  }

  static const char* value(const ::subt_ros::CompetitionClock_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_ros::CompetitionClock_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.phase);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CompetitionClock_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_ros::CompetitionClock_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_ros::CompetitionClock_<ContainerAllocator>& v)
  {
    s << indent << "phase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.phase);
    s << indent << "data: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_ROS_MESSAGE_COMPETITIONCLOCK_H
