// Generated by gencpp from file subt_ros/RobotEvent.msg
// DO NOT EDIT!


#ifndef SUBT_ROS_MESSAGE_ROBOTEVENT_H
#define SUBT_ROS_MESSAGE_ROBOTEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_ros
{
template <class ContainerAllocator>
struct RobotEvent_
{
  typedef RobotEvent_<ContainerAllocator> Type;

  RobotEvent_()
    : timestamp()
    , event_type()
    , robot_name()
    , event_id(0)  {
    }
  RobotEvent_(const ContainerAllocator& _alloc)
    : timestamp()
    , event_type(_alloc)
    , robot_name(_alloc)
    , event_id(0)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type_type;
  _event_type_type event_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef int32_t _event_id_type;
  _event_id_type event_id;





  typedef boost::shared_ptr< ::subt_ros::RobotEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_ros::RobotEvent_<ContainerAllocator> const> ConstPtr;

}; // struct RobotEvent_

typedef ::subt_ros::RobotEvent_<std::allocator<void> > RobotEvent;

typedef boost::shared_ptr< ::subt_ros::RobotEvent > RobotEventPtr;
typedef boost::shared_ptr< ::subt_ros::RobotEvent const> RobotEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_ros::RobotEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_ros::RobotEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_ros::RobotEvent_<ContainerAllocator1> & lhs, const ::subt_ros::RobotEvent_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.event_type == rhs.event_type &&
    lhs.robot_name == rhs.robot_name &&
    lhs.event_id == rhs.event_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_ros::RobotEvent_<ContainerAllocator1> & lhs, const ::subt_ros::RobotEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_ros::RobotEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_ros::RobotEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_ros::RobotEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_ros::RobotEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_ros::RobotEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_ros::RobotEvent_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_ros::RobotEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc10551a4500913b19b42b632423ffbb";
  }

  static const char* value(const ::subt_ros::RobotEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc10551a4500913bULL;
  static const uint64_t static_value2 = 0x19b42b632423ffbbULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_ros::RobotEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_ros/RobotEvent";
  }

  static const char* value(const ::subt_ros::RobotEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_ros::RobotEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# An event representing an interesting occurrence for an individual robot\n"
"\n"
"time timestamp 		# time since sim bootup\n"
"string event_type	# type of event (\"detach\" for marsupials, \"breadcrumb_deploy\" for breadcrumbs, \"dead_battery\", or \"flip\")\n"
"string robot_name	# name of the robot that triggered the event\n"
"int32 event_id		# Unique ID of the event\n"
;
  }

  static const char* value(const ::subt_ros::RobotEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_ros::RobotEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.event_type);
      stream.next(m.robot_name);
      stream.next(m.event_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_ros::RobotEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_ros::RobotEvent_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "event_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event_type);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "event_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.event_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_ROS_MESSAGE_ROBOTEVENT_H
