blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Relesase
devel_layout: linked
devel_space: devel
extend_path: /home/admin-vras/workspace/cras_subt/devel
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
