(cl:in-package subt_ros-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          REPORTED_ARTIFACT_TYPE-VAL
          REPORTED_ARTIFACT_TYPE
          REPORTED_ARTIFACT_POSITION-VAL
          REPORTED_ARTIFACT_POSITION
          CLOSEST_ARTIFACT_NAME-VAL
          CLOSEST_ARTIFACT_NAME
          DISTANCE-VAL
          DISTANCE
          POINTS_SCORED-VAL
          POINTS_SCORED
          TOTAL_SCORE-VAL
          TOTAL_SCORE
))