// Generated by gencpp from file subt_virtual/StepSimulation.msg
// DO NOT EDIT!


#ifndef SUBT_VIRTUAL_MESSAGE_STEPSIMULATION_H
#define SUBT_VIRTUAL_MESSAGE_STEPSIMULATION_H

#include <ros/service_traits.h>


#include <subt_virtual/StepSimulationRequest.h>
#include <subt_virtual/StepSimulationResponse.h>


namespace subt_virtual
{

struct StepSimulation
{

typedef StepSimulationRequest Request;
typedef StepSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepSimulation
} // namespace subt_virtual


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_virtual::StepSimulation > {
  static const char* value()
  {
    return "acade967e80a92511f0f34ceb5b30047";
  }

  static const char* value(const ::subt_virtual::StepSimulation&) { return value(); }
};

template<>
struct DataType< ::subt_virtual::StepSimulation > {
  static const char* value()
  {
    return "subt_virtual/StepSimulation";
  }

  static const char* value(const ::subt_virtual::StepSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::subt_virtual::StepSimulationRequest> should match
// service_traits::MD5Sum< ::subt_virtual::StepSimulation >
template<>
struct MD5Sum< ::subt_virtual::StepSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_virtual::StepSimulation >::value();
  }
  static const char* value(const ::subt_virtual::StepSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_virtual::StepSimulationRequest> should match
// service_traits::DataType< ::subt_virtual::StepSimulation >
template<>
struct DataType< ::subt_virtual::StepSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::subt_virtual::StepSimulation >::value();
  }
  static const char* value(const ::subt_virtual::StepSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_virtual::StepSimulationResponse> should match
// service_traits::MD5Sum< ::subt_virtual::StepSimulation >
template<>
struct MD5Sum< ::subt_virtual::StepSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_virtual::StepSimulation >::value();
  }
  static const char* value(const ::subt_virtual::StepSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_virtual::StepSimulationResponse> should match
// service_traits::DataType< ::subt_virtual::StepSimulation >
template<>
struct DataType< ::subt_virtual::StepSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::subt_virtual::StepSimulation >::value();
  }
  static const char* value(const ::subt_virtual::StepSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_VIRTUAL_MESSAGE_STEPSIMULATION_H
