// Generated by gencpp from file subt_virtual/StepSimulationRequest.msg
// DO NOT EDIT!


#ifndef SUBT_VIRTUAL_MESSAGE_STEPSIMULATIONREQUEST_H
#define SUBT_VIRTUAL_MESSAGE_STEPSIMULATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_virtual
{
template <class ContainerAllocator>
struct StepSimulationRequest_
{
  typedef StepSimulationRequest_<ContainerAllocator> Type;

  StepSimulationRequest_()
    : num_steps(0)  {
    }
  StepSimulationRequest_(const ContainerAllocator& _alloc)
    : num_steps(0)  {
  (void)_alloc;
    }



   typedef uint32_t _num_steps_type;
  _num_steps_type num_steps;





  typedef boost::shared_ptr< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StepSimulationRequest_

typedef ::subt_virtual::StepSimulationRequest_<std::allocator<void> > StepSimulationRequest;

typedef boost::shared_ptr< ::subt_virtual::StepSimulationRequest > StepSimulationRequestPtr;
typedef boost::shared_ptr< ::subt_virtual::StepSimulationRequest const> StepSimulationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_virtual::StepSimulationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_virtual::StepSimulationRequest_<ContainerAllocator1> & lhs, const ::subt_virtual::StepSimulationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num_steps == rhs.num_steps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_virtual::StepSimulationRequest_<ContainerAllocator1> & lhs, const ::subt_virtual::StepSimulationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_virtual

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c00bc357dda60c1b215e553c5d1cdb5b";
  }

  static const char* value(const ::subt_virtual::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc00bc357dda60c1bULL;
  static const uint64_t static_value2 = 0x215e553c5d1cdb5bULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_virtual/StepSimulationRequest";
  }

  static const char* value(const ::subt_virtual::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 num_steps\n"
;
  }

  static const char* value(const ::subt_virtual::StepSimulationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepSimulationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_virtual::StepSimulationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_virtual::StepSimulationRequest_<ContainerAllocator>& v)
  {
    s << indent << "num_steps: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_steps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_VIRTUAL_MESSAGE_STEPSIMULATIONREQUEST_H
