// Generated by gencpp from file subt_example/CreatePeerRequest.msg
// DO NOT EDIT!


#ifndef SUBT_EXAMPLE_MESSAGE_CREATEPEERREQUEST_H
#define SUBT_EXAMPLE_MESSAGE_CREATEPEERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_example
{
template <class ContainerAllocator>
struct CreatePeerRequest_
{
  typedef CreatePeerRequest_<ContainerAllocator> Type;

  CreatePeerRequest_()
    : remote()  {
    }
  CreatePeerRequest_(const ContainerAllocator& _alloc)
    : remote(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _remote_type;
  _remote_type remote;





  typedef boost::shared_ptr< ::subt_example::CreatePeerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_example::CreatePeerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CreatePeerRequest_

typedef ::subt_example::CreatePeerRequest_<std::allocator<void> > CreatePeerRequest;

typedef boost::shared_ptr< ::subt_example::CreatePeerRequest > CreatePeerRequestPtr;
typedef boost::shared_ptr< ::subt_example::CreatePeerRequest const> CreatePeerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_example::CreatePeerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_example::CreatePeerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_example::CreatePeerRequest_<ContainerAllocator1> & lhs, const ::subt_example::CreatePeerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.remote == rhs.remote;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_example::CreatePeerRequest_<ContainerAllocator1> & lhs, const ::subt_example::CreatePeerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_example

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_example::CreatePeerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_example::CreatePeerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_example::CreatePeerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80761590f205a620f53bc694424a10d6";
  }

  static const char* value(const ::subt_example::CreatePeerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80761590f205a620ULL;
  static const uint64_t static_value2 = 0xf53bc694424a10d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_example/CreatePeerRequest";
  }

  static const char* value(const ::subt_example::CreatePeerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string remote\n"
;
  }

  static const char* value(const ::subt_example::CreatePeerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remote);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreatePeerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_example::CreatePeerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_example::CreatePeerRequest_<ContainerAllocator>& v)
  {
    s << indent << "remote: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.remote);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_EXAMPLE_MESSAGE_CREATEPEERREQUEST_H
