// Generated by gencpp from file subt_example/CreatePeerResponse.msg
// DO NOT EDIT!


#ifndef SUBT_EXAMPLE_MESSAGE_CREATEPEERRESPONSE_H
#define SUBT_EXAMPLE_MESSAGE_CREATEPEERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_example
{
template <class ContainerAllocator>
struct CreatePeerResponse_
{
  typedef CreatePeerResponse_<ContainerAllocator> Type;

  CreatePeerResponse_()
    {
    }
  CreatePeerResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::subt_example::CreatePeerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_example::CreatePeerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CreatePeerResponse_

typedef ::subt_example::CreatePeerResponse_<std::allocator<void> > CreatePeerResponse;

typedef boost::shared_ptr< ::subt_example::CreatePeerResponse > CreatePeerResponsePtr;
typedef boost::shared_ptr< ::subt_example::CreatePeerResponse const> CreatePeerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_example::CreatePeerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_example::CreatePeerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace subt_example

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_example::CreatePeerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_example::CreatePeerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_example::CreatePeerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::subt_example::CreatePeerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_example/CreatePeerResponse";
  }

  static const char* value(const ::subt_example::CreatePeerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::subt_example::CreatePeerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CreatePeerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_example::CreatePeerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::subt_example::CreatePeerResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_EXAMPLE_MESSAGE_CREATEPEERRESPONSE_H
