// Generated by gencpp from file subt_msgs/BindRequest.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_BINDREQUEST_H
#define SUBT_MSGS_MESSAGE_BINDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct BindRequest_
{
  typedef BindRequest_<ContainerAllocator> Type;

  BindRequest_()
    : address()
    , endpoint()  {
    }
  BindRequest_(const ContainerAllocator& _alloc)
    : address(_alloc)
    , endpoint(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _endpoint_type;
  _endpoint_type endpoint;





  typedef boost::shared_ptr< ::subt_msgs::BindRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::BindRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BindRequest_

typedef ::subt_msgs::BindRequest_<std::allocator<void> > BindRequest;

typedef boost::shared_ptr< ::subt_msgs::BindRequest > BindRequestPtr;
typedef boost::shared_ptr< ::subt_msgs::BindRequest const> BindRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::BindRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::BindRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::BindRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::BindRequest_<ContainerAllocator2> & rhs)
{
  return lhs.address == rhs.address &&
    lhs.endpoint == rhs.endpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::BindRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::BindRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::BindRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::BindRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::BindRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::BindRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::BindRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::BindRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::BindRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f83d3516fd8ab9984c9d0affc8172d6d";
  }

  static const char* value(const ::subt_msgs::BindRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf83d3516fd8ab998ULL;
  static const uint64_t static_value2 = 0x4c9d0affc8172d6dULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::BindRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/BindRequest";
  }

  static const char* value(const ::subt_msgs::BindRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::BindRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Bind\n"
"\n"
"string address\n"
"string endpoint\n"
;
  }

  static const char* value(const ::subt_msgs::BindRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::BindRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.endpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BindRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::BindRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::BindRequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
    s << indent << "endpoint: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.endpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_BINDREQUEST_H
