// Generated by gencpp from file subt_msgs/Bind.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_BIND_H
#define SUBT_MSGS_MESSAGE_BIND_H

#include <ros/service_traits.h>


#include <subt_msgs/BindRequest.h>
#include <subt_msgs/BindResponse.h>


namespace subt_msgs
{

struct Bind
{

typedef BindRequest Request;
typedef BindResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Bind
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::Bind > {
  static const char* value()
  {
    return "a0b5e26f9a30fd733cf49d2f9152fc7e";
  }

  static const char* value(const ::subt_msgs::Bind&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::Bind > {
  static const char* value()
  {
    return "subt_msgs/Bind";
  }

  static const char* value(const ::subt_msgs::Bind&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::BindRequest> should match
// service_traits::MD5Sum< ::subt_msgs::Bind >
template<>
struct MD5Sum< ::subt_msgs::BindRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::Bind >::value();
  }
  static const char* value(const ::subt_msgs::BindRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::BindRequest> should match
// service_traits::DataType< ::subt_msgs::Bind >
template<>
struct DataType< ::subt_msgs::BindRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::Bind >::value();
  }
  static const char* value(const ::subt_msgs::BindRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::BindResponse> should match
// service_traits::MD5Sum< ::subt_msgs::Bind >
template<>
struct MD5Sum< ::subt_msgs::BindResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::Bind >::value();
  }
  static const char* value(const ::subt_msgs::BindResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::BindResponse> should match
// service_traits::DataType< ::subt_msgs::Bind >
template<>
struct DataType< ::subt_msgs::BindResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::Bind >::value();
  }
  static const char* value(const ::subt_msgs::BindResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_BIND_H
