// Generated by gencpp from file subt_msgs/DatagramRos.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_DATAGRAMROS_H
#define SUBT_MSGS_MESSAGE_DATAGRAMROS_H

#include <ros/service_traits.h>


#include <subt_msgs/DatagramRosRequest.h>
#include <subt_msgs/DatagramRosResponse.h>


namespace subt_msgs
{

struct DatagramRos
{

typedef DatagramRosRequest Request;
typedef DatagramRosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DatagramRos
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::DatagramRos > {
  static const char* value()
  {
    return "9b49f58b9703cbf5a2ea81c4d815a945";
  }

  static const char* value(const ::subt_msgs::DatagramRos&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::DatagramRos > {
  static const char* value()
  {
    return "subt_msgs/DatagramRos";
  }

  static const char* value(const ::subt_msgs::DatagramRos&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::DatagramRosRequest> should match
// service_traits::MD5Sum< ::subt_msgs::DatagramRos >
template<>
struct MD5Sum< ::subt_msgs::DatagramRosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::DatagramRos >::value();
  }
  static const char* value(const ::subt_msgs::DatagramRosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::DatagramRosRequest> should match
// service_traits::DataType< ::subt_msgs::DatagramRos >
template<>
struct DataType< ::subt_msgs::DatagramRosRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::DatagramRos >::value();
  }
  static const char* value(const ::subt_msgs::DatagramRosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::DatagramRosResponse> should match
// service_traits::MD5Sum< ::subt_msgs::DatagramRos >
template<>
struct MD5Sum< ::subt_msgs::DatagramRosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::DatagramRos >::value();
  }
  static const char* value(const ::subt_msgs::DatagramRosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::DatagramRosResponse> should match
// service_traits::DataType< ::subt_msgs::DatagramRos >
template<>
struct DataType< ::subt_msgs::DatagramRosResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::DatagramRos >::value();
  }
  static const char* value(const ::subt_msgs::DatagramRosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_DATAGRAMROS_H
