// Generated by gencpp from file subt_msgs/PoseFromArtifactRequest.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_POSEFROMARTIFACTREQUEST_H
#define SUBT_MSGS_MESSAGE_POSEFROMARTIFACTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace subt_msgs
{
template <class ContainerAllocator>
struct PoseFromArtifactRequest_
{
  typedef PoseFromArtifactRequest_<ContainerAllocator> Type;

  PoseFromArtifactRequest_()
    : robot_name()  {
    }
  PoseFromArtifactRequest_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _robot_name_type;
  _robot_name_type robot_name;





  typedef boost::shared_ptr< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PoseFromArtifactRequest_

typedef ::subt_msgs::PoseFromArtifactRequest_<std::allocator<void> > PoseFromArtifactRequest;

typedef boost::shared_ptr< ::subt_msgs::PoseFromArtifactRequest > PoseFromArtifactRequestPtr;
typedef boost::shared_ptr< ::subt_msgs::PoseFromArtifactRequest const> PoseFromArtifactRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a714a45eb282cdb6b20eb8ead90c5b9a";
  }

  static const char* value(const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa714a45eb282cdb6ULL;
  static const uint64_t static_value2 = 0xb20eb8ead90c5b9aULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/PoseFromArtifactRequest";
  }

  static const char* value(const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PoseFromArtifact\n"
"\n"
"std_msgs/String robot_name\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseFromArtifactRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::PoseFromArtifactRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_POSEFROMARTIFACTREQUEST_H
