// Generated by gencpp from file subt_msgs/Register.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_REGISTER_H
#define SUBT_MSGS_MESSAGE_REGISTER_H

#include <ros/service_traits.h>


#include <subt_msgs/RegisterRequest.h>
#include <subt_msgs/RegisterResponse.h>


namespace subt_msgs
{

struct Register
{

typedef RegisterRequest Request;
typedef RegisterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Register
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::Register > {
  static const char* value()
  {
    return "8055bcc6948a0bb447d53fea3837f962";
  }

  static const char* value(const ::subt_msgs::Register&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::Register > {
  static const char* value()
  {
    return "subt_msgs/Register";
  }

  static const char* value(const ::subt_msgs::Register&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::RegisterRequest> should match
// service_traits::MD5Sum< ::subt_msgs::Register >
template<>
struct MD5Sum< ::subt_msgs::RegisterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::Register >::value();
  }
  static const char* value(const ::subt_msgs::RegisterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::RegisterRequest> should match
// service_traits::DataType< ::subt_msgs::Register >
template<>
struct DataType< ::subt_msgs::RegisterRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::Register >::value();
  }
  static const char* value(const ::subt_msgs::RegisterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::RegisterResponse> should match
// service_traits::MD5Sum< ::subt_msgs::Register >
template<>
struct MD5Sum< ::subt_msgs::RegisterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::Register >::value();
  }
  static const char* value(const ::subt_msgs::RegisterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::RegisterResponse> should match
// service_traits::DataType< ::subt_msgs::Register >
template<>
struct DataType< ::subt_msgs::RegisterResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::Register >::value();
  }
  static const char* value(const ::subt_msgs::RegisterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_REGISTER_H
