// Generated by gencpp from file subt_msgs/SetPose.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_SETPOSE_H
#define SUBT_MSGS_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <subt_msgs/SetPoseRequest.h>
#include <subt_msgs/SetPoseResponse.h>


namespace subt_msgs
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::SetPose > {
  static const char* value()
  {
    return "e75fa6b5606a256e6021356eef2fa1e5";
  }

  static const char* value(const ::subt_msgs::SetPose&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::SetPose > {
  static const char* value()
  {
    return "subt_msgs/SetPose";
  }

  static const char* value(const ::subt_msgs::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::SetPoseRequest> should match
// service_traits::MD5Sum< ::subt_msgs::SetPose >
template<>
struct MD5Sum< ::subt_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::SetPose >::value();
  }
  static const char* value(const ::subt_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::SetPoseRequest> should match
// service_traits::DataType< ::subt_msgs::SetPose >
template<>
struct DataType< ::subt_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::SetPose >::value();
  }
  static const char* value(const ::subt_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::SetPoseResponse> should match
// service_traits::MD5Sum< ::subt_msgs::SetPose >
template<>
struct MD5Sum< ::subt_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::SetPose >::value();
  }
  static const char* value(const ::subt_msgs::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::SetPoseResponse> should match
// service_traits::DataType< ::subt_msgs::SetPose >
template<>
struct DataType< ::subt_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::SetPose >::value();
  }
  static const char* value(const ::subt_msgs::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_SETPOSE_H
