// Generated by gencpp from file subt_msgs/SetRate.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_SETRATE_H
#define SUBT_MSGS_MESSAGE_SETRATE_H

#include <ros/service_traits.h>


#include <subt_msgs/SetRateRequest.h>
#include <subt_msgs/SetRateResponse.h>


namespace subt_msgs
{

struct SetRate
{

typedef SetRateRequest Request;
typedef SetRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRate
} // namespace subt_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::subt_msgs::SetRate > {
  static const char* value()
  {
    return "4910f3d55cbb29566b6c8f8f16528adf";
  }

  static const char* value(const ::subt_msgs::SetRate&) { return value(); }
};

template<>
struct DataType< ::subt_msgs::SetRate > {
  static const char* value()
  {
    return "subt_msgs/SetRate";
  }

  static const char* value(const ::subt_msgs::SetRate&) { return value(); }
};


// service_traits::MD5Sum< ::subt_msgs::SetRateRequest> should match
// service_traits::MD5Sum< ::subt_msgs::SetRate >
template<>
struct MD5Sum< ::subt_msgs::SetRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::SetRate >::value();
  }
  static const char* value(const ::subt_msgs::SetRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::SetRateRequest> should match
// service_traits::DataType< ::subt_msgs::SetRate >
template<>
struct DataType< ::subt_msgs::SetRateRequest>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::SetRate >::value();
  }
  static const char* value(const ::subt_msgs::SetRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::subt_msgs::SetRateResponse> should match
// service_traits::MD5Sum< ::subt_msgs::SetRate >
template<>
struct MD5Sum< ::subt_msgs::SetRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::subt_msgs::SetRate >::value();
  }
  static const char* value(const ::subt_msgs::SetRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::subt_msgs::SetRateResponse> should match
// service_traits::DataType< ::subt_msgs::SetRate >
template<>
struct DataType< ::subt_msgs::SetRateResponse>
{
  static const char* value()
  {
    return DataType< ::subt_msgs::SetRate >::value();
  }
  static const char* value(const ::subt_msgs::SetRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_SETRATE_H
