// Generated by gencpp from file subt_msgs/SetRateRequest.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_SETRATEREQUEST_H
#define SUBT_MSGS_MESSAGE_SETRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct SetRateRequest_
{
  typedef SetRateRequest_<ContainerAllocator> Type;

  SetRateRequest_()
    : rate(0.0)  {
    }
  SetRateRequest_(const ContainerAllocator& _alloc)
    : rate(0.0)  {
  (void)_alloc;
    }



   typedef double _rate_type;
  _rate_type rate;





  typedef boost::shared_ptr< ::subt_msgs::SetRateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::SetRateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRateRequest_

typedef ::subt_msgs::SetRateRequest_<std::allocator<void> > SetRateRequest;

typedef boost::shared_ptr< ::subt_msgs::SetRateRequest > SetRateRequestPtr;
typedef boost::shared_ptr< ::subt_msgs::SetRateRequest const> SetRateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::SetRateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::SetRateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::SetRateRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::SetRateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.rate == rhs.rate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::SetRateRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::SetRateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::SetRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::SetRateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::SetRateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4910f3d55cbb29566b6c8f8f16528adf";
  }

  static const char* value(const ::subt_msgs::SetRateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4910f3d55cbb2956ULL;
  static const uint64_t static_value2 = 0x6b6c8f8f16528adfULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/SetRateRequest";
  }

  static const char* value(const ::subt_msgs::SetRateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 rate\n"
;
  }

  static const char* value(const ::subt_msgs::SetRateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::SetRateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::SetRateRequest_<ContainerAllocator>& v)
  {
    s << indent << "rate: ";
    Printer<double>::stream(s, indent + "  ", v.rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_SETRATEREQUEST_H
