// Generated by gencpp from file subt_msgs/UnregisterRequest.msg
// DO NOT EDIT!


#ifndef SUBT_MSGS_MESSAGE_UNREGISTERREQUEST_H
#define SUBT_MSGS_MESSAGE_UNREGISTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace subt_msgs
{
template <class ContainerAllocator>
struct UnregisterRequest_
{
  typedef UnregisterRequest_<ContainerAllocator> Type;

  UnregisterRequest_()
    : local_address()  {
    }
  UnregisterRequest_(const ContainerAllocator& _alloc)
    : local_address(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _local_address_type;
  _local_address_type local_address;





  typedef boost::shared_ptr< ::subt_msgs::UnregisterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::subt_msgs::UnregisterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UnregisterRequest_

typedef ::subt_msgs::UnregisterRequest_<std::allocator<void> > UnregisterRequest;

typedef boost::shared_ptr< ::subt_msgs::UnregisterRequest > UnregisterRequestPtr;
typedef boost::shared_ptr< ::subt_msgs::UnregisterRequest const> UnregisterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::subt_msgs::UnregisterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::subt_msgs::UnregisterRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::UnregisterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.local_address == rhs.local_address;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::subt_msgs::UnregisterRequest_<ContainerAllocator1> & lhs, const ::subt_msgs::UnregisterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace subt_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::subt_msgs::UnregisterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::subt_msgs::UnregisterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::subt_msgs::UnregisterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16f42c66531aa48735faf75e2640f4c2";
  }

  static const char* value(const ::subt_msgs::UnregisterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16f42c66531aa487ULL;
  static const uint64_t static_value2 = 0x35faf75e2640f4c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "subt_msgs/UnregisterRequest";
  }

  static const char* value(const ::subt_msgs::UnregisterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Unregister\n"
"\n"
"string local_address\n"
;
  }

  static const char* value(const ::subt_msgs::UnregisterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UnregisterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::subt_msgs::UnregisterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::subt_msgs::UnregisterRequest_<ContainerAllocator>& v)
  {
    s << indent << "local_address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.local_address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUBT_MSGS_MESSAGE_UNREGISTERREQUEST_H
